batch_size: 256
max_iter: 50000
lr: 0.001
lr_min: 0.0001
log_every: 10
val_every: 1000
val_num: 10
save_every: 5000
grad_clip: 10.0

test_grasp_num: 100
test_topk: 10

model:
  name: BaseModel
  backbone:
    name: WrappedMinkUNet
    out_feat_dim: 1024
    voxel_size: 0.005
  grasp_type_emb:
    name: LearnableTypeCond
    out_feat_dim: 128
    in_feat_dim: ${..backbone.out_feat_dim}
    use_predictor: false
    disabled: false
  head:
    name: FlowRT_MLPRTJ
    in_feat_dim:
    kp_dim: 84
    joint_num:  ${....data.joint_num}
    traj_length: ${....data.traj_length}
    mobius:
      layer: 24
      k: 32
 
loss_weight:
  loss_nll: 1.0  
  loss_trans: 1.0
  loss_rot: 1.0
  loss_joint: 1.0 
  loss_fm: 1.0 
  loss_vq: 1.0